<!doctype html>
<html lang="fr">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="This is a dinamic page generated by the team InfoTech, Tout droit reservé!!">
    <meta name="author" content="InfoTech">

    <title>Fly party</title>

    <!-- CSS FILES -->
    <link rel="preconnect" href="https://fonts.googleapis.com">

    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@100;200;400;700&display=swap" rel="stylesheet">

    <link href="css/bootstrap.min.css" rel="stylesheet">

    <link href="css/bootstrap-icons.css" rel="stylesheet">

    <link href="css/templatemo-festava-live.css" rel="stylesheet">
    <!--

TemplateMo 583 Festava Live

https://templatemo.com/tm-583-festava-live

-->

</head>

<body>

    <main>

        <header class="site-header">
            <div class="container">
                <div class="row">

                    <div class="col-lg-12 col-12 d-flex flex-wrap">
                        <p class="d-flex me-4 mb-0">
                            <i class="bi-person custom-icon me-2"></i>
                            <strong class="text-dark">Bienvenue sur Fly Party 2024</strong>
                        </p>
                    </div>

                </div>
            </div>
        </header>


        <nav class="navbar navbar-expand-lg">
            <div class="container">
                <a class="navbar-brand" href="/">
                    Fly Party
                </a>

                <a href="<?php echo 'ticket' ?>" class="btn custom-btn d-lg-none ms-auto me-4">Achat Ticket</a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav align-items-lg-center ms-auto me-lg-5">
                        <li class="nav-item">
                            <a class="nav-link click-scroll" href="<?php echo '/'?> ">Menu</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link click-scroll" href="/#section_2">A propos</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link click-scroll" href="/#section_3">Artists</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link click-scroll" href="/#section_4">Evenements</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link click-scroll" href="/#section_5">Prix</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link click-scroll" href="/#section_6">Contact</a>
                        </li>
                    </ul>

                    <a href="/ticket" class="btn custom-btn d-lg-block d-none">Achat ticket</a>
                </div>
            </div>
        </nav>


        <section class="ticket-section section-padding">
            <div class="section-overlay"></div>

            <div class="container">
                <div class="row">

                    <div class="col-lg-6 col-10 mx-auto">
                        <form class="custom-form ticket-form mb-5 mb-lg-0" action="/billet" method="POST">
                            @csrf
                            @if(Session::has('success'))
                <div class="alert alert-success">{{Session::get('success')}}</div>
                @endif
                @if (Session::has('fail'))
                    
                <div class="alert alert-error">{{Session::get('fail')}}</div>
                    @endif
                
                
                            <h2 class="text-center mb-4">Commencé ici!</h2>
                            <p style="font-size: 13px">(Toute les informations collecté seront utilisé par notre équipe pour validé votre commande <br>Aucun information ne sera partagé ailleurs)</p>

                            <div class="ticket-form-body">
                                <div class="row">
                                    <div class="col-lg-6 col-md-6 col-12">
                                        <input type="text" name="nom" id="ticket-form-name"
                                        
                                            class="form-control" placeholder="Votre nom complet" >
                                            <span class="text-danger">@error('name') {{ $message }} @enderror </span>
                                    </div>

                                    <div class="col-lg-6 col-md-6 col-12">
                                        <input type="email" name="email" id="email"
                                            pattern="[^ @]*@[^ @]*" class="form-control" placeholder="Email "
                                            required="">
                                            <span class="text-danger">@error('email') {{ $message }} @enderror </span>
                                    </div>
                                </div>

                                <input type="tel" class="form-control" name="phone"
                                    placeholder="Tel (Ex*MG 0350098566)"  required="">
                                    <span class="text-danger">@error('number') {{ $message }} @enderror </span>

                                <h6>Type de ticket</h6>

                                <div class="row">
                                    <div class="col-lg-6 col-md-6 col-12">
                                        <div class="form-check form-control">
                                            <input class="form-check-input" value="20.000Ar" type="radio" name="TicketForm"
                                                id="flexRadioDefault1">
                                            <label class="form-check-label" for="flexRadioDefault1">
                                                basique 20.000Ar
                                            </label>
                                        </div>
                                    </div>

                                    <div class="col-lg-6 col-md-6 col-12">
                                        <div class="form-check form-check-radio form-control">
                                            <input class="form-check-input" type="radio" name="TicketForm"
                                              value="30.000Ar"  id="flexRadioDefault2">
                                            <label class="form-check-label" for="flexRadioDefault2">
                                                V.I.P 30.000Ar
                                            </label>
                                        </div>
                                    </div>
                                </div>

                                <input type="number" name="NbrTicket" id="ticket-form-number"
                                    class="form-control" placeholder="Nombre de ticket" required="">
                                    <span class="text-danger">@error('Ticket') {{ $message }} @enderror </span>

                                <textarea name="demande" rows="3" class="form-control" value="0"
                                    id="ticket-form-message" placeholder="Requête spécifique? (Merci de mettre un '0' si aucun)"></textarea>

                                <div class="col-lg-4 col-md-10 col-8 mx-auto">
                                    <button type="submit" class="form-control">Acheter ticket</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
        </section>
    </main>


    <footer class="site-footer">
        <div class="site-footer-top">
            <div class="container">
                <div class="row">

                    <div class="col-lg-6 col-12">
                        <h2 class="text-white mb-lg-0">Fly Party</h2>
                    </div>

                    <div class="col-lg-6 col-12 d-flex justify-content-lg-end align-items-center">
                        <ul class="social-icon d-flex justify-content-lg-end">
                            <li class="social-icon-item">
                                <a href="#" class="social-icon-link">
                                    <span class="bi-twitter"></span>
                                </a>
                            </li>

                            <li class="social-icon-item">
                                <a href="#" class="social-icon-link">
                                    <span class="bi-apple"></span>
                                </a>
                            </li>

                            <li class="social-icon-item">
                                <a href="#" class="social-icon-link">
                                    <span class="bi-instagram"></span>
                                </a>
                            </li>

                            <li class="social-icon-item">
                                <a href="#" class="social-icon-link">
                                    <span class="bi-youtube"></span>
                                </a>
                            </li>

                            <li class="social-icon-item">
                                <a href="#" class="social-icon-link">
                                    <span class="bi-pinterest"></span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div class="container">
            <div class="row">

                <div class="col-lg-6 col-12 mb-4 pb-2">
                    <h5 class="site-footer-title mb-3">Liens</h5>

                    <ul class="site-footer-links">
                        <li class="site-footer-link-item">
                            <a href="/" class="site-footer-link">Menu</a>
                        </li>

                        <li class="site-footer-link-item">
                            <a href="#" class="site-footer-link">A propos</a>
                        </li>

                        <li class="site-footer-link-item">
                            <a href="#" class="site-footer-link">Artiste</a>
                        </li>

                        <li class="site-footer-link-item">
                            <a href="#" class="site-footer-link">Evenements</a>
                        </li>

                        <li class="site-footer-link-item">
                            <a href="#" class="site-footer-link">Prix</a>
                        </li>

                        <li class="site-footer-link-item">
                            <a href="#" class="site-footer-link">Contact</a>
                        </li>
                    </ul>
                </div>

                <div class="col-lg-3 col-md-6 col-12 mb-4 mb-lg-0">
                    <h5 class="site-footer-title mb-3">Des question?</h5>

                    <p class="text-white d-flex mb-1">
                        <a href="tel: 033-34-823-87" class="site-footer-link">
                            033-34-823-87
                        </a>
                    </p>

                    <p class="text-white d-flex">
                        <a href="mailto:hello@company.com" class="site-footer-link">
                            PartyFly@company.com
                        </a>
                    </p>
                </div>

                <div class="col-lg-3 col-md-6 col-11 mb-4 mb-lg-0 mb-md-0">
                    <h5 class="site-footer-title mb-3">Location</h5>

                    <p class="text-white d-flex mt-3 mb-2">
                        Madagascar,Antananarivo,Antaninarenina</p>

                    <a class="link-fx-1 color-contrast-higher mt-3" href="#">
                        <span>Où nous trouver?</span>
                        <svg class="icon" viewBox="0 0 32 32" aria-hidden="true">
                            <g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round">
                                <circle cx="16" cy="16" r="15.5"></circle>
                                <line x1="10" y1="18" x2="16" y2="12"></line>
                                <line x1="16" y1="12" x2="22" y2="18"></line>
                            </g>
                        </svg>
                    </a>
                </div>
            </div>
        </div>

        <div class="site-footer-bottom">
            <div class="container">
                <div class="row">

                    <div class="col-lg-3 col-12 mt-5">
                        <p class="copyright-text">Copyright © 2023 Fly Party Company</p>
                    </div>

                    <div class="col-lg-8 col-12 mt-lg-5">
                        <ul class="site-footer-links">
                            <li class="site-footer-link-item">
                                <a href="#" class="site-footer-link">Terms &amp; Conditions</a>
                            </li>

                            <li class="site-footer-link-item">
                                <a href="#" class="site-footer-link">Privacy Policy</a>
                            </li>

                            <li class="site-footer-link-item">
                                <a href="#" class="site-footer-link">Commentaires</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <!--

T e m p l a t e M o

-->
    <!-- JAVASCRIPT FILES -->
    <script src="js/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/jquery.sticky.js"></script>
    <script src="js/custom.js"></script>

</body>

</html>